services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
      - "0.0.0.0:5174:5173" #can remove later
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    develop:
      watch:
      - path: ./frontend
        target: /app
        action: sync
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    ports:
      - "5000:5000"
      - "0.0.0.0:5001:5000" #can remove later
      - "8888:8888"

    env_file: 
      - ./backend/.env
    develop:
      watch:
      - path: ./backend
        target: /app
        action: sync
    volumes:
      - ./uploads:/app/uploads        

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  nextcloud_data:
  redis_data:
  pip-cache: