services:
  frontend:
    build: ./frontend
    ports: 
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    develop:
      watch:
      - path: ./frontend
        target: /app
        action: sync 
    stdin_open: true #for the live reload in react to work
    tty: true
  backend:
    build: ./backend
    ports:
      - "5000:5000"

    env_file: 
      - ./backend/.env

    develop:
      watch:
      - path: ./backend
        target: /app
        action: sync

    volumes:
      - ./uploads:/app/uploads
  